opencti:
  url: 'http://localhost:4000'
  token: '815dd7b7-1b96-4cb1-9b0e-27d9a3d88fdb'

connector:
  id: '2c6ffa90-fe27-4aaf-93db-dcec0d0ec553'
  type: 'INTERNAL_EXPORT_FILE'
  name: 'ExportFileCsv'
  scope: 'text/csv'
  confidence_level: 3
  log_level: 'info'