version: '3'
services:
  connector-alienvault:
    image: opencti/connector-alienvault:3.1.0
    environment:
      - OPENCTI_URL=http://localhost:4000
      - OPENCTI_TOKEN=815dd7b7-1b96-4cb1-9b0e-27d9a3d88fdb
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=AlienVault
      - CONNECTOR_SCOPE=alienvault
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_LOG_LEVEL=info
      - ALIENVAULT_BASE_URL=https://otx.alienvault.com
      - ALIENVAULT_API_KEY=046efd9268661e0ac97bd6f0b4cb238ec3dbc869cf26ccafdf17ed3927fbf5c4
      - ALIENVAULT_TLP=White
      - ALIENVAULT_PULSE_START_TIMESTAMP=2020-01-01T00:00:00 # BEWARE! Could be a lot of pulses!
      - ALIENVAULT_REPORT_TYPE=Threat Report
      - ALIENVAULT_REPORT_STATUS=Analyzed
      - ALIENVAULT_GUESS_MALWARE=false # Use tags to guess malware.
      - ALIENVAULT_INTERVAL_SEC=1800
    restart: always
    network_mode: "host"
