opencti:
  url: 'http://localhost:4000'
  token: '815dd7b7-1b96-4cb1-9b0e-27d9a3d88fdb'

connector:
  id: '6152b0fe-9f87-4445-9a45-b767669b5d48'
  type: 'EXTERNAL_IMPORT'
  name: 'MITRE ATT&CK'
  scope: 'identity,attack-pattern,course-of-action,intrusion-set,malware,tool,report'
  confidence_level: 3
  update_existing_data: True
  log_level: 'info'

mitre:
  enterprise_file_url: 'https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json'
  pre_attack_file_url: 'https://raw.githubusercontent.com/mitre/cti/master/pre-attack/pre-attack.json'
  interval: 3 # Days