version: '3'
services:
  worker:
    image: opencti/worker:3.1.0
    environment:
      - OPENCTI_URL=http://localhost:4000
      - OPENCTI_TOKEN=815dd7b7-1b96-4cb1-9b0e-27d9a3d88fdb
      - WORKER_LOG_LEVEL=info
    restart: always
    network_mode: "host"