version: '3'
services:
  connector-virustotal:
    image: opencti/connector-virustotal:3.1.0
    environment:
      - OPENCTI_URL=http://localhost:4000
      - OPENCTI_TOKEN=815dd7b7-1b96-4cb1-9b0e-27d9a3d88fdb
      - CONNECTOR_ID=82f6ef51-24cd-498a-ad47-f6039d603c79
      - CONNECTOR_TYPE=INTERNAL_ENRICHMENT
      - CONNECTOR_NAME=VirusTotal
      - CONNECTOR_SCOPE='file-md5,file-sha1,file-sha256'
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_LOG_LEVEL=info
      - VIRUSTOTAL_TOKEN=907c37f0ab21398a4b98651e094c65a2ad183188892bd098bbd74f92b27864d9
      - VIRUSTOTAL_MAX_TLP=TLP:AMBER
    restart: always