opencti:
  url: 'http://localhost:4000'
  token: '815dd7b7-1b96-4cb1-9b0e-27d9a3d88fdb'

connector:
  id: '8007e551-f1bb-4be8-8a55-0a6d08b7a1e5'
  type: 'EXTERNAL_IMPORT'
  name: 'AM!TT'
  scope: 'identity,attack-pattern,course-of-action,intrusion-set,malware,tool,report'
  confidence_level: 3
  update_existing_data: True
  log_level: 'info'

amitt:
  amitt_file_url: 'https://raw.githubusercontent.com/VVX7/cti/master/amitt-attack/amitt-attack.json'
  pre_amitt_file_url: 'https://raw.githubusercontent.com/VVX7/cti/master/amitt-pre-attack/amitt-pre-attack.json'
  interval: 7 # Days