version: '3'
services:
  connector-cyber-threat-coalition:
    image: opencti/connector-cyber-threat-coalition:3.1.0
    environment:
      - OPENCTI_URL=http://localhost:4000
      - OPENCTI_TOKEN=815dd7b7-1b96-4cb1-9b0e-27d9a3d88fdb
      - CONNECTOR_ID=7956d04b-a0c6-4d1c-93da-4e41493733f6
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=CyberThreatCoalition
      - CONNECTOR_SCOPE=indicator,report,identity
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_LOG_LEVEL=info
      - CYBER_THREAT_COALITION_INTERVAL=21600 # Seconds (6 hours)
      - CYBER_THREAT_COALITION_BASE_URL=https://blacklist.cyberthreatcoalition.org/vetted
    restart: always