version: '3'
services:
  connector-ipinfo:
    image: opencti/connector-ipinfo:3.1.0
    environment:
      - OPENCTI_URL=http://localhost:4000
      - OPENCTI_TOKEN=815dd7b7-1b96-4cb1-9b0e-27d9a3d88fdb
      - CONNECTOR_ID=a51a46a2-a14c-48f5-8d80-636e5f88ebfa
      - CONNECTOR_TYPE=INTERNAL_ENRICHMENT
      - CONNECTOR_NAME=IpInfo
      - CONNECTOR_SCOPE='ipv4-addr'
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_LOG_LEVEL=info
      - IPINFO_TOKEN=1f78624ff7a9fe
      - IPINFO_MAX_TLP=TLP:AMBER
    restart: always
    network_mode: "host"