version: '3'
services:
  connector-cryptolaemus:
    image: opencti/connector-cryptolaemus:3.1.0
    environment:
      - OPENCTI_URL=http://localhost:4000
      - OPENCTI_TOKEN=815dd7b7-1b96-4cb1-9b0e-27d9a3d88fdb
      - CONNECTOR_ID=cd3b85de-7ab1-41dc-b108-7c149ccaa3a2
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=Cryptolaemus
      - CONNECTOR_SCOPE=cryptolaemus
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
    restart: always