opencti:
  url: 'http://localhost:4000'
  token: '815dd7b7-1b96-4cb1-9b0e-27d9a3d88fdb'

connector:
  id: '468dfb69-ba64-4642-8a56-a4312e26e7be'
  type: 'EXTERNAL_IMPORT'
  name: 'Common Vulnerabilities and Exposures'
  scope: 'identity,vulnerability'
  confidence_level: 3
  update_existing_data: True
  log_level: 'info'

cve:
  nvd_data_feed: 'https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-recent.json.gz'
  history_data_feed: 'https://nvd.nist.gov/feeds/json/cve/1.1/'
  interval: 7 # Days
