opencti:
  url: 'http://localhost:4000'
  token: '815dd7b7-1b96-4cb1-9b0e-27d9a3d88fdb'

connector:
  id: 'cd3b85de-7ab1-41dc-b108-7c149ccaa3a2'
  type: 'EXTERNAL_IMPORT'
  name: 'Cryptolaemus'
  scope: 'cryptolaemus'
  confidence_level: 3
  log_level: 'info'